### ISSUE TITLE
Support for React 17

### ISSUE THREAD

**Issue by ale917k** [sstur/react-rte#415]
Since upgrading to React 17, the package manager flags about a difference in peer dependency version for react:
`react-rte@0.16.3" has incorrect peer dependency "react@0.14.x || 15.x.x || 16.x.x".`
`react-rte@0.16.3" has incorrect peer dependency "react-dom@0.14.x || 15.x.x || 16.x.x".`

Can the dependency be updated accordingly? [No new feature changes have been introduced](https://reactjs.org/blog/2020/10/20/react-v17.html), thus no breaking changes can be introduced with the upgrade

**Comment by machineghost** [comment]
That ticket seems to have been fixed since June; what exactly is being waited for (in November)?

**Comment by sstur** [comment]
Done. This was released with [v0.16.4](https://github.com/sstur/react-rte/releases/tag/v0.16.4)

**Comment by joeyzhousherwin** [comment]
Hi @sstur , I'm trying to install react-rte, but my project is already at react 17.0.2. 

Is there anyway i can install it? i tried `npm i react-rte`, but it wouldn't let me

**Comment by erikt9** [comment]
I think you'll probably need to do it with `npm install --legacy-peer-deps react-rte` as the package.json hasn't been updated to use say React 17 is supported.

**Comment by the-serious-programmer** [comment]
@sstur this issue still exists. 

```
  "peerDependencies": {
    "react": "0.14.x || 15.x.x || 16.x.x",
    "react-dom": "0.14.x || 15.x.x || 16.x.x"
  },
```
`|| 17.x.x` needs to be added to this for the above issue to be truly resolved

**Comment by sstur** [comment]
Oops, it looks like I need to cut a new release to npm. That is now done. Thanks!
